// GENERATED by tool/emit_legal.dart — do not edit by hand.
//
// The source is lib/features/settings/presentation/legal_content.dart,
// which is what the app itself renders. Change the policy there and
// re-run the script, so the page a regulator reads and the page a user
// reads cannot say different things.

export interface LegalBlock {
  readonly text: string;
  readonly heading: boolean;
}

export const LEGAL_UPDATED = "3 September 2026";
export const LEGAL_CONTACT = "REPLACE-WITH-YOUR-SUPPORT-EMAIL";

export const PRIVACY_POLICY: readonly LegalBlock[] = [
  { text: "Last updated: 3 September 2026", heading: false },
  { text: "Carbsai is operated by REPLACE-WITH-YOUR-LEGAL-NAME. This policy explains what the app collects, where it goes, and what you can do about it. It describes what the app actually does — if something here is not true of the app you are using, tell us at REPLACE-WITH-YOUR-SUPPORT-EMAIL.", heading: false },
  { text: "1. What we collect", heading: true },
  { text: "• Account: your email address and display name. Your password is handled by Firebase Authentication and is never visible to us.", heading: false },
  { text: "• About you: age, sex, height, weight, activity level, goal and what brought you to the app, from the questions asked when you sign up. They are used to calculate your calorie target, and — if you build a meal plan — your targets, goal and diet preference are sent with that request to our AI provider so the plan fits them. Every question is skippable.", heading: false },
  { text: "• Your taste, if you use the plan builder: which dishes you tapped, the this-or-that answers, the foods you asked to leave out, how much time you have to cook, and anything you typed in the notes box. These are sent to our AI provider to write the plan. Foods you exclude are a health-adjacent choice, so we keep them under your account, never share them with advertisers, and never use them for ad targeting.", heading: false },
  { text: "• Your diary: the meals you log, the foods and portions in them, when you ate, and any photograph you take.", heading: false },
  { text: "• Your weight, if you record it.", heading: false },
  { text: "• Scan records: for each AI scan, which model ran, how many tokens it used, what it cost, what the model said, and the note or description you typed with it. This is how we keep the service affordable and improve accuracy. It is stored under your account and is not readable by the app.", heading: false },
  { text: "• Plan records: for each meal plan, which model ran, what it cost, and a summary of the answers as counts and categories — how many dishes you tapped, which exclusions you chose, which cook time. What you typed in the notes box is never written to this record.", heading: false },
  { text: "• Adverts: if you are not a Premium subscriber, Google AdMob may collect your device’s advertising identifier and technical information to show and cap adverts. On iOS you are asked first, and on Android and in the EEA and UK a consent form runs before any advert is requested. Premium accounts never initialise the advertising SDK at all.", heading: false },
  { text: "We do not use a third-party analytics or crash-reporting SDK, and we do not collect your location or your contacts.", heading: false },
  { text: "2. Where your data goes", heading: true },
  { text: "• Google Firebase (Authentication and Cloud Firestore) stores your account and everything in it.", heading: false },
  { text: "• Cloudflare Workers runs our server: every AI request passes through it, and it holds the daily cost counters. Meal photographs are kept on your phone; they are not uploaded to us.", heading: false },
  { text: "• Our AI provider (currently OpenRouter, routing to OpenAI) receives the photograph or written description of your meal and any note you add, in order to estimate its nutrition; and, when you build a meal plan, your calorie and macro targets, your goal, your diet preference and your answers in the plan builder. It does not receive your name, your email or your account identifier. This is the most significant thing the app does with your data, and it happens only when you scan a meal, describe one, or build a plan.", heading: false },
  { text: "• The USDA FoodData Central database and Open Food Facts receive your search terms and scanned barcodes — the words or numbers only, with nothing that identifies you.", heading: false },
  { text: "• Google AdMob, for adverts, as described above.", heading: false },
  { text: "These providers process data on our behalf, or independently in the case of advertising. This means your data may be processed outside your country, including in the United States. We do not sell your personal data, and we do not use it to train AI models.", heading: false },
  { text: "3. Why we are allowed to", heading: true },
  { text: "Where the UK or EU GDPR applies: we process your account and diary to perform our contract with you; we use adverts and store scan records on the basis of our legitimate interest in running a sustainable free tier and improving accuracy; and personalised advertising runs only with your consent, which you can withdraw.", heading: false },
  { text: "4. How long we keep it", heading: true },
  { text: "Your data is kept while your account exists. Delete your account and it goes with it — the diary, the photographs, the scan records, the plan records, the subscription record and the account itself. Deletion runs immediately and is not reversible. Some records we are legally required to keep, such as proof of a transaction, are kept for as long as the law requires.", heading: false },
  { text: "5. Your rights", heading: true },
  { text: "You can ask for a copy of your data, ask us to correct or delete it, object to how we use it, or ask us to restrict it. Write to REPLACE-WITH-YOUR-SUPPORT-EMAIL and we will reply within one month. You can also complain to your data protection regulator.", heading: false },
  { text: "You can delete everything yourself, at any time, from Settings → More → Delete Account. You do not have to ask us.", heading: false },
  { text: "6. Security", heading: true },
  { text: "Data is encrypted in transit. Our servers reach your data with per-account rules that prevent one account from reading another’s. No system is perfectly secure, but we do not hold payment card details at any point — the stores handle payment.", heading: false },
  { text: "7. Children", heading: true },
  { text: "Carbsai is not for children under 13. If you believe a child has given us personal data, write to REPLACE-WITH-YOUR-SUPPORT-EMAIL and we will delete it.", heading: false },
  { text: "8. Changes", heading: true },
  { text: "If we change this policy we will update the date above and, for a material change, tell you in the app before it takes effect.", heading: false },
  { text: "9. Contact", heading: true },
  { text: "REPLACE-WITH-YOUR-SUPPORT-EMAIL", heading: false },
];

export const TERMS: readonly LegalBlock[] = [
  { text: "Last updated: 3 September 2026", heading: false },
  { text: "Carbsai is operated by REPLACE-WITH-YOUR-LEGAL-NAME. Please read these Terms before using the app. By creating an account or using Carbsai, you agree to them. If you do not agree, do not use the app.", heading: false },
  { text: "1. Who can use Carbsai", heading: true },
  { text: "You must be at least 13 years old. If you are under 18, use Carbsai only with the consent of a parent or guardian. Carbsai is not designed for children and we do not knowingly collect data from anyone under 13.", heading: false },
  { text: "2. Carbsai is not medical advice", heading: true },
  { text: "Carbsai estimates the nutrition in your food and suggests calorie and macronutrient targets. It is not a medical device, not a healthcare provider, and not a substitute for professional advice.", heading: false },
  { text: "• Speak to a doctor or a registered dietitian before starting any diet, especially if you are pregnant, have an eating disorder, diabetes, or any other medical condition.", heading: false },
  { text: "• Do not use Carbsai to manage a medical condition or to decide on medication.", heading: false },
  { text: "3. Estimates are estimates", heading: true },
  { text: "Nutrition figures produced from a photograph or a description are generated by an AI model and are approximate. Published evaluations of the best vision models on food photographs report average errors of roughly a third on calories and higher on individual macronutrients. Carbsai shows how confident it is and lets you correct any figure; corrected values are the ones your diary counts. Treat every number as a guide, not a measurement.", heading: false },
  { text: "4. Your account", heading: true },
  { text: "• Give accurate information and keep it up to date.", heading: false },
  { text: "• Keep your password to yourself. You are responsible for what happens under your account.", heading: false },
  { text: "• Do not share an account, or use somebody else’s.", heading: false },
  { text: "• You can delete your account at any time from Settings → More → Delete Account. This removes your account and your data. It cannot be undone.", heading: false },
  { text: "5. Subscriptions and payment", heading: true },
  { text: "Carbsai Premium is sold as an auto-renewing subscription through the Apple App Store or Google Play. The store takes the payment, not us.", heading: false },
  { text: "• Payment is charged to your store account at confirmation of purchase.", heading: false },
  { text: "• The subscription renews automatically unless you cancel at least 24 hours before the end of the current period, and your account is charged for renewal within that window.", heading: false },
  { text: "• Manage or cancel a subscription in your App Store or Google Play account settings. Uninstalling the app does not cancel it.", heading: false },
  { text: "• Refunds are handled by the store under its own policy. We cannot issue them.", heading: false },
  { text: "• Prices may change. We will tell you before a change affects a renewal.", heading: false },
  { text: "6. Free scans, ads and rewards", heading: true },
  { text: "Free accounts get a fixed allowance of AI scans — three at the time of writing — which does not renew, and up to three AI meal plans a day. You can earn extra scans by watching a rewarded advert, up to a daily limit. Searching the food database, scanning a barcode, describing a meal in words and entering food by hand are unlimited and always free. Premium accounts get a monthly scan allowance and see no adverts at all. We may change these allowances; the app always shows what you have left.", heading: false },
  { text: "7. Acceptable use", heading: true },
  { text: "Do not:", heading: false },
  { text: "• Try to break, overload, reverse-engineer or gain unauthorised access to the app or its servers.", heading: false },
  { text: "• Use automated tools to make scans, or otherwise work around the scan allowance.", heading: false },
  { text: "• Upload anything unlawful, or anyone else’s photographs.", heading: false },
  { text: "We may suspend or close an account that does, without a refund.", heading: false },
  { text: "8. Your content", heading: true },
  { text: "Your photographs and diary entries remain yours. You give us permission to process them only so far as is needed to run the app for you — which includes sending a food photograph to our AI provider to be analysed. We do not use your photographs to train AI models, and we do not sell them.", heading: false },
  { text: "9. Availability and liability", heading: true },
  { text: "Carbsai is provided as it is. We do not promise it will be uninterrupted or error-free, and we depend on services we do not control. To the extent the law allows, we are not liable for indirect or consequential loss, or for any health outcome arising from following an estimate. Nothing here limits liability that cannot lawfully be limited.", heading: false },
  { text: "10. Changes and ending", heading: true },
  { text: "We may change these Terms; material changes will be shown in the app before they take effect. You can stop using Carbsai at any time. We may end your access if you break these Terms.", heading: false },
  { text: "11. Governing law", heading: true },
  { text: "These Terms are governed by the law of REPLACE-WITH-YOUR-JURISDICTION.", heading: false },
  { text: "12. Contact", heading: true },
  { text: "REPLACE-WITH-YOUR-SUPPORT-EMAIL", heading: false },
];

