// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTo7js4DzYmHf9oYlPnNgbiL6WnbJgQpI',
    appId: '1:539925326951:web:7d8b1438dd253221aab8c2',
    messagingSenderId: '539925326951',
    projectId: 'carbsai-8cca8',
    authDomain: 'carbsai-8cca8.firebaseapp.com',
    storageBucket: 'carbsai-8cca8.firebasestorage.app',
    measurementId: 'G-M69SR8GPY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDzGTnrFx4oQPVjrTh5Y2G3iNnGmyK7yM',
    appId: '1:539925326951:android:8e4942c7e90734daaab8c2',
    messagingSenderId: '539925326951',
    projectId: 'carbsai-8cca8',
    storageBucket: 'carbsai-8cca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACSC6nQ9KLMLGQvmGZCGGo93cSOwPb3K0',
    appId: '1:539925326951:ios:95257d120a37b3f8aab8c2',
    messagingSenderId: '539925326951',
    projectId: 'carbsai-8cca8',
    storageBucket: 'carbsai-8cca8.firebasestorage.app',
    iosBundleId: 'com.carbsai.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACSC6nQ9KLMLGQvmGZCGGo93cSOwPb3K0',
    appId: '1:539925326951:ios:416dfc7f85910501aab8c2',
    messagingSenderId: '539925326951',
    projectId: 'carbsai-8cca8',
    storageBucket: 'carbsai-8cca8.firebasestorage.app',
    iosBundleId: 'com.example.carbsai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTo7js4DzYmHf9oYlPnNgbiL6WnbJgQpI',
    appId: '1:539925326951:web:f4856e7d177845ceaab8c2',
    messagingSenderId: '539925326951',
    projectId: 'carbsai-8cca8',
    authDomain: 'carbsai-8cca8.firebaseapp.com',
    storageBucket: 'carbsai-8cca8.firebasestorage.app',
    measurementId: 'G-NN5BHR7Y4B',
  );
}
