// Emits the Worker's copy of the legal documents from the app's own copy.
//
// Play needs a privacy policy at a public URL before it will accept a listing,
// and it must describe the same app the binary is. `legal_content.dart` already
// does — it is hand-written and `legal_content_test.dart` holds it to what this
// repository actually does with data.
//
// So the web copy is generated from it rather than written twice. The taxonomy
// is the cautionary tale: it exists in Dart and TypeScript and needs a test
// reading one as text to keep them honest. Here the Dart is pure — no Flutter
// import — so a script can import it directly and emit the exact strings, and
// there is nothing to drift.
//
//   dart run tool/emit_legal.dart
//
// Writes workers/src/legal.ts. Rendering lives in the Worker, hand-written;
// this file carries only the words.

import 'dart:io';

import '../lib/features/settings/presentation/legal_content.dart';

void main() {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/emit_legal.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// The source is lib/features/settings/presentation/legal_content.dart,')
    ..writeln('// which is what the app itself renders. Change the policy there and')
    ..writeln('// re-run the script, so the page a regulator reads and the page a user')
    ..writeln('// reads cannot say different things.')
    ..writeln()
    ..writeln('export interface LegalBlock {')
    ..writeln('  readonly text: string;')
    ..writeln('  readonly heading: boolean;')
    ..writeln('}')
    ..writeln()
    ..writeln('export const LEGAL_UPDATED = ${_ts(LegalOperator.updated)};')
    ..writeln('export const LEGAL_CONTACT = ${_ts(LegalOperator.email)};')
    ..writeln();

  _emit(buffer, 'PRIVACY_POLICY', privacyPolicy);
  _emit(buffer, 'TERMS', termsAndConditions);

  File('workers/src/legal.ts').writeAsStringSync(buffer.toString());
  stdout.writeln('wrote workers/src/legal.ts '
      '(${privacyPolicy.length} privacy blocks, ${termsAndConditions.length} terms blocks)');

  // Loud, not silent. A policy served with these in it is worse than no policy:
  // it is a public document naming an operator that does not exist.
  if (buffer.toString().contains('REPLACE-WITH-YOUR')) {
    stdout.writeln(
      '\n  WARNING: LegalOperator still holds placeholders, so the Worker will\n'
      '  refuse to serve these pages. Fill name, email and jurisdiction in\n'
      '  lib/features/settings/presentation/legal_content.dart and re-run.\n',
    );
  }
}

void _emit(StringBuffer out, String name, List<LegalBlock> blocks) {
  out.writeln('export const $name: readonly LegalBlock[] = [');
  for (final block in blocks) {
    out.writeln('  { text: ${_ts(block.text)}, heading: ${block.isHeading} },');
  }
  out
    ..writeln('];')
    ..writeln();
}

/// A TypeScript double-quoted string literal.
String _ts(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll('"', r'\"')
      .replaceAll('\n', r'\n');
  return '"$escaped"';
}
