// Long-form copy for Figma frames `43_Terms and Conditions` (2002:804),
// `44_Privacy Policy` (2002:781) and `45_Help` (2002:757).
//
// This file WAS generated from the artboards. It is hand-written now, and
// deliberately so: the extracted copy described a different app.
//
// The privacy policy said the operator's name was "us." — a placeholder that
// was never filled — and disclosed sharing with "Google Fit, Apple Health, if
// you authorize them", neither of which this app integrates with. Meanwhile it
// disclosed none of what actually happens: a photograph of the user's food
// leaves the device and is sent to a third-party AI provider. That is the most
// significant thing this app does with personal data, and the one thing the
// policy did not mention. Both stores' review processes check a policy against
// the app's declared data practices, and an inaccurate policy is a rejection
// as well as a legal exposure.
//
// The copy below describes what the code in this repository actually does. If
// you change where data goes — a new provider, an analytics SDK, a health
// integration — change this too, in the same commit.
//
// NOT LEGAL ADVICE. Have a lawyer read it before release, and fill in
// [LegalOperator] first.

/// The three facts a policy cannot be written without.
///
/// **All three are placeholders and must be replaced before release.** They are
/// deliberately obvious rather than plausible: a wrong-but-plausible support
/// address ships silently, whereas this one does not survive a read-through.
///
/// The email must be a real inbox someone reads. Both stores require a working
/// contact route for privacy requests, and the GDPR gives people a right to a
/// reply within a month.
abstract final class LegalOperator {
  /// The legal entity that operates the app — a company or a named individual.
  static const String name = 'Lumy Labs';

  /// A monitored inbox for privacy and support requests.
  static const String email = 'lumylabsco@gmail.com';

  /// Whose law governs, e.g. "England and Wales", "Pakistan".
  static const String jurisdiction = 'Pakistan';

  /// Shown at the top of both documents. Update whenever the copy changes —
  /// a policy whose date predates the practices it describes reads as stale.
  static const String updated = '3 September 2026';
}

/// One block of a legal page. [isHeading] blocks are the 17pt section titles;
/// the rest is 15pt body copy.
class LegalBlock {
  const LegalBlock(this.text, {this.isHeading = false});

  final String text;
  final bool isHeading;
}

/// Terms and Conditions.
const List<LegalBlock> termsAndConditions = [
  LegalBlock('Last updated: ${LegalOperator.updated}'),
  LegalBlock(
    'Carbs AI is operated by ${LegalOperator.name}. Please read these Terms '
    'before using the app. By creating an account or using Carbs AI, you agree '
    'to them. If you do not agree, do not use the app.',
  ),

  LegalBlock('1. Who can use Carbs AI', isHeading: true),
  LegalBlock(
    'You must be at least 13 years old. If you are under 18, use Carbs AI only '
    'with the consent of a parent or guardian. Carbs AI is not designed for '
    'children and we do not knowingly collect data from anyone under 13.',
  ),

  LegalBlock('2. Carbs AI is not medical advice', isHeading: true),
  LegalBlock(
    'Carbs AI estimates the nutrition in your food and suggests calorie and '
    'macronutrient targets. It is not a medical device, not a healthcare '
    'provider, and not a substitute for professional advice.',
  ),
  LegalBlock(
    '• Speak to a doctor or a registered dietitian before starting any diet, '
    'especially if you are pregnant, have an eating disorder, diabetes, or any '
    'other medical condition.',
  ),
  LegalBlock(
    '• Do not use Carbs AI to manage a medical condition or to decide on '
    'medication.',
  ),

  LegalBlock('3. Estimates are estimates', isHeading: true),
  LegalBlock(
    'Nutrition figures produced from a photograph or a description are '
    'generated by an AI model and are approximate. Published evaluations of '
    'the best vision models on food photographs report average errors of '
    'roughly a third on calories and higher on individual macronutrients. '
    'Carbs AI shows how confident it is and lets you correct any figure; '
    'corrected values are the ones your diary counts. Treat every number as a '
    'guide, not a measurement.',
  ),

  LegalBlock('4. Your account', isHeading: true),
  LegalBlock('• Give accurate information and keep it up to date.'),
  LegalBlock(
    '• Keep your password to yourself. You are responsible for what happens '
    'under your account.',
  ),
  LegalBlock('• Do not share an account, or use somebody else’s.'),
  LegalBlock(
    '• You can delete your account at any time from Settings → More '
    '→ Delete Account. This removes your account and your data. It cannot '
    'be undone.',
  ),

  LegalBlock('5. Subscriptions and payment', isHeading: true),
  LegalBlock(
    'Carbs AI Premium is sold as an auto-renewing subscription through the '
    'Apple App Store or Google Play. The store takes the payment, not us.',
  ),
  LegalBlock(
    '• Payment is charged to your store account at confirmation of purchase.',
  ),
  LegalBlock(
    '• The subscription renews automatically unless you cancel at least 24 '
    'hours before the end of the current period, and your account is charged '
    'for renewal within that window.',
  ),
  LegalBlock(
    '• Manage or cancel a subscription in your App Store or Google Play '
    'account settings. Uninstalling the app does not cancel it.',
  ),
  LegalBlock(
    '• Refunds are handled by the store under its own policy. We cannot issue '
    'them.',
  ),
  LegalBlock(
    '• Prices may change. We will tell you before a change affects a renewal.',
  ),

  LegalBlock('6. Free scans, ads and rewards', isHeading: true),
  LegalBlock(
    'Free accounts get a fixed allowance of AI scans — three at the time of '
    'writing — which does not renew, and up to three AI meal plans a day. You '
    'can earn extra scans by watching a rewarded advert, up to a daily limit. '
    'Searching the food database, scanning a barcode, describing a meal in '
    'words and entering food by hand are unlimited and always free. Premium '
    'accounts get a monthly scan allowance and see no adverts at all. We may '
    'change these allowances; the app always shows what you have left.',
  ),

  LegalBlock('7. Acceptable use', isHeading: true),
  LegalBlock('Do not:'),
  LegalBlock(
    '• Try to break, overload, reverse-engineer or gain unauthorised access to '
    'the app or its servers.',
  ),
  LegalBlock(
    '• Use automated tools to make scans, or otherwise work around the scan '
    'allowance.',
  ),
  LegalBlock('• Upload anything unlawful, or anyone else’s photographs.'),
  LegalBlock(
    'We may suspend or close an account that does, without a refund.',
  ),

  LegalBlock('8. Your content', isHeading: true),
  LegalBlock(
    'Your photographs and diary entries remain yours. You give us permission '
    'to process them only so far as is needed to run the app for you — which '
    'includes sending a food photograph to our AI provider to be analysed. We '
    'do not use your photographs to train AI models, and we do not sell them.',
  ),

  LegalBlock('9. Availability and liability', isHeading: true),
  LegalBlock(
    'Carbs AI is provided as it is. We do not promise it will be uninterrupted '
    'or error-free, and we depend on services we do not control. To the extent '
    'the law allows, we are not liable for indirect or consequential loss, or '
    'for any health outcome arising from following an estimate. Nothing here '
    'limits liability that cannot lawfully be limited.',
  ),

  LegalBlock('10. Changes and ending', isHeading: true),
  LegalBlock(
    'We may change these Terms; material changes will be shown in the app '
    'before they take effect. You can stop using Carbs AI at any time. We may '
    'end your access if you break these Terms.',
  ),

  LegalBlock('11. Governing law', isHeading: true),
  LegalBlock(
    'These Terms are governed by the law of ${LegalOperator.jurisdiction}.',
  ),

  LegalBlock('12. Contact', isHeading: true),
  LegalBlock(LegalOperator.email),
];

/// Privacy Policy.
const List<LegalBlock> privacyPolicy = [
  LegalBlock('Last updated: ${LegalOperator.updated}'),
  LegalBlock(
    'Carbs AI is operated by ${LegalOperator.name}. This policy explains what '
    'the app collects, where it goes, and what you can do about it. It '
    'describes what the app actually does — if something here is not true of '
    'the app you are using, tell us at ${LegalOperator.email}.',
  ),

  LegalBlock('1. What we collect', isHeading: true),
  LegalBlock(
    '• Account: your email address and display name. Your password is handled '
    'by Firebase Authentication and is never visible to us.',
  ),
  LegalBlock(
    '• About you: age, sex, height, weight, activity level, goal and what '
    'brought you to the app, from the questions asked when you sign up. They '
    'are used to calculate your calorie target, and — if you build a meal '
    'plan — your targets, goal and diet preference are sent with that request '
    'to our AI provider so the plan fits them. Every question is skippable.',
  ),
  LegalBlock(
    '• Your taste, if you use the plan builder: which dishes you tapped, the '
    'this-or-that answers, the foods you asked to leave out, how much time '
    'you have to cook, and anything you typed in the notes box. These are '
    'sent to our AI provider to write the plan. Foods you exclude are a '
    'health-adjacent choice, so we keep them under your account, never share '
    'them with advertisers, and never use them for ad targeting.',
  ),
  LegalBlock(
    '• Your diary: the meals you log, the foods and portions in them, when you '
    'ate, and any photograph you take.',
  ),
  LegalBlock('• Your weight, if you record it.'),
  LegalBlock(
    '• Your water and activity log, if you record them: how much you drank '
    'and when, and what exercise you did, for how long, and our estimate of '
    'what it cost you. All of it stays in your own account and none of it is '
    'sent to the AI provider or to anyone else.',
  ),
  LegalBlock(
    '• Scan records: for each AI scan, which model ran, how many tokens it '
    'used, what it cost, what the model said, and the note or description you '
    'typed with it. This is how we keep the service affordable and improve '
    'accuracy. It is stored under your account and is not readable by the app.',
  ),
  LegalBlock(
    '• Plan records: for each meal plan, which model ran, what it cost, and a '
    'summary of the answers as counts and categories — how many dishes you '
    'tapped, which exclusions you chose, which cook time. What you typed in '
    'the notes box is never written to this record.',
  ),
  LegalBlock(
    '• Adverts: if you are not a Premium subscriber, Google AdMob may collect '
    'your device’s advertising identifier and technical information to '
    'show and cap adverts. On iOS you are asked first, and on Android and in '
    'the EEA and UK a consent form runs before any advert is requested. '
    'Premium accounts never initialise the advertising SDK at all.',
  ),
  LegalBlock(
    '• Crash reports: if the app stops unexpectedly, Firebase Crashlytics '
    'sends Google a report of what went wrong — the error, the sequence of '
    'code that led to it, and the device model and operating system version. '
    'It is not tied to your account: we do not attach your user identifier, '
    'so a crash report cannot be traced back to you. Nothing from your diary, '
    'your photographs or your profile is included.',
  ),
  LegalBlock(
    'We do not use a third-party analytics SDK, we do not track what you do '
    'inside the app, and we do not collect your location or your contacts.',
  ),

  LegalBlock('2. Where your data goes', isHeading: true),
  LegalBlock(
    '• Google Firebase (Authentication and Cloud Firestore) stores your '
    'account and everything in it.',
  ),
  LegalBlock(
    '• Cloudflare Workers runs our server: every AI request passes through it, '
    'and it holds the daily cost counters. Meal photographs are kept on your '
    'phone; they are not uploaded to us.',
  ),
  LegalBlock(
    '• Our AI provider (currently OpenRouter, routing to OpenAI) receives the '
    'photograph or written description of your meal and any note you add, in '
    'order to estimate its nutrition; and, when you build a meal plan, your '
    'calorie and macro targets, your goal, your diet preference and your '
    'answers in the plan builder. It does not receive your name, your email '
    'or your account identifier. This is the most significant thing the app '
    'does with your data, and it happens only when you scan a meal, describe '
    'one, or build a plan.',
  ),
  LegalBlock(
    '• The USDA FoodData Central database and Open Food Facts receive your '
    'search terms and scanned barcodes — the words or numbers only, with '
    'nothing that identifies you.',
  ),
  LegalBlock(
    '• Google AdMob, for adverts, as described above.',
  ),
  LegalBlock(
    '• Firebase Crashlytics, also Google, receives a crash report when the '
    'app stops unexpectedly, as described above.',
  ),
  LegalBlock(
    'These providers process data on our behalf, or independently in the case '
    'of advertising. This means your data may be processed outside your '
    'country, including in the United States. We do not sell your personal '
    'data, and we do not use it to train AI models.',
  ),

  LegalBlock('3. Why we are allowed to', isHeading: true),
  LegalBlock(
    'Where the UK or EU GDPR applies: we process your account and diary to '
    'perform our contract with you; we use adverts and store scan records on '
    'the basis of our legitimate interest in running a sustainable free tier '
    'and improving accuracy; and personalised advertising runs only with your '
    'consent, which you can withdraw.',
  ),

  LegalBlock('4. How long we keep it', isHeading: true),
  LegalBlock(
    'Your data is kept while your account exists. Delete your account and it '
    'goes with it — the diary, the photographs, the scan records, the plan '
    'records, the subscription record and the account itself. Deletion runs '
    'immediately and is not reversible. Some records we are legally required '
    'to keep, such as proof of a transaction, are kept for as long as the law '
    'requires.',
  ),

  LegalBlock('5. Your rights', isHeading: true),
  LegalBlock(
    'You can ask for a copy of your data, ask us to correct or delete it, '
    'object to how we use it, or ask us to restrict it. Write to '
    '${LegalOperator.email} and we will reply within one month. You can also '
    'complain to your data protection regulator.',
  ),
  LegalBlock(
    'You can delete everything yourself, at any time, from Settings → '
    'More → Delete Account. You do not have to ask us.',
  ),

  LegalBlock('6. Security', isHeading: true),
  LegalBlock(
    'Data is encrypted in transit. Our servers reach your data with '
    'per-account rules that prevent one account from reading another’s. '
    'No system is perfectly secure, but we do not hold payment card details at '
    'any point — the stores handle payment.',
  ),

  LegalBlock('7. Children', isHeading: true),
  LegalBlock(
    'Carbs AI is not for children under 13. If you believe a child has given us '
    'personal data, write to ${LegalOperator.email} and we will delete it.',
  ),

  LegalBlock('8. Changes', isHeading: true),
  LegalBlock(
    'If we change this policy we will update the date above and, for a '
    'material change, tell you in the app before it takes effect.',
  ),

  LegalBlock('9. Contact', isHeading: true),
  LegalBlock(LegalOperator.email),
];

/// Help — Figma frame content.
const List<LegalBlock> help = [
  LegalBlock('We\'re here to guide you every step of the way.'),
  LegalBlock('Quick Help Topics', isHeading: true),
  LegalBlock('How to log a meal'),
  LegalBlock('      Step-by-step guide to track your food'),
  LegalBlock('Setting your calorie goal'),
  LegalBlock('      Learn how Carbs AI calculates your targets'),
  LegalBlock('Choosing a diet plan'),
  LegalBlock('      Understand what works best for your goals'),
  LegalBlock('Contact Support', isHeading: true),
  LegalBlock('Can’t find what you\'re looking for?'),
  LegalBlock(LegalOperator.email),
  LegalBlock('We usually respond within 24 hours.'),
  LegalBlock('Helpful Links', isHeading: true),
  LegalBlock('Privacy Policy'),
  LegalBlock('Terms & Conditions'),
];

/// How to delete an account, as a page on the web.
///
/// Play will not accept a listing from an app that creates accounts without a
/// URL where deletion can be requested, and it checks three things: that the
/// page names the app, that the steps are prominent, and that it says what is
/// deleted and what is kept.
///
/// That last one is why this is written against `workers/src/account.ts` rather
/// than from memory. Everything under `users/{uid}` goes, including the
/// subcollections the client cannot even read. `purchases/{sha256}` does not —
/// it lives outside that subtree and is what recognises a refund notice from a
/// store after the account is gone. A page claiming everything is erased while
/// that row remains would be a claim rather than a disclosure.
///
/// It lives here rather than in the Worker so that the words a person reads on
/// the web come from the same file as the words they read in the app.
const List<LegalBlock> accountDeletion = [
  LegalBlock(
    'This page explains how to delete your Carbs AI account and the data held '
    'with it.',
  ),

  LegalBlock('Delete it yourself, in the app', isHeading: true),
  LegalBlock('1. Open Carbs AI and sign in.'),
  LegalBlock('2. Go to Settings.'),
  LegalBlock('3. Tap “Delete account” and confirm.'),
  LegalBlock(
    'Deletion runs on our server rather than on your phone, so it finishes '
    'even if you uninstall the app straight afterwards. The app waits for it '
    'and tells you if anything could not be removed.',
  ),

  LegalBlock('Ask us instead', isHeading: true),
  LegalBlock(
    'If you cannot sign in — a lost password, a phone you no longer have — '
    'email ${LegalOperator.email} from the address on the account, with '
    '“Delete my account” as the subject. We will confirm and delete it within '
    '30 days.',
  ),

  LegalBlock('What is deleted', isHeading: true),
  LegalBlock(
    '• Your profile: name, email address, date of birth, sex, height, weight, '
    'activity level, goal and calorie targets.',
  ),
  LegalBlock('• Your food diary: every meal, with its figures and its photo.'),
  LegalBlock('• Diet plans you built or saved, and your favourites.'),
  LegalBlock('• Your weight history.'),
  LegalBlock('• Your water and activity logs.'),
  LegalBlock('• Notifications and reminder preferences.'),
  LegalBlock(
    '• Records you were never able to see yourself: the scan log, your scan '
    'quota and your subscription entitlement.',
  ),
  LegalBlock('• Any meal photographs held in our storage.'),
  LegalBlock(
    '• The sign-in account itself, so the email address can be used again from '
    'scratch.',
  ),
  LegalBlock(
    'All of it goes at once. There is no grace period and nothing is archived.',
  ),

  LegalBlock('What is kept, and why', isHeading: true),
  LegalBlock(
    '• If you ever subscribed, we keep a one-way hash of the store’s purchase '
    'identifier. It is what lets us recognise a refund or cancellation notice '
    'from Google or Apple after the account is gone. It holds no name, no '
    'email address and nothing from your diary, and it cannot be turned back '
    'into your purchase.',
  ),
  LegalBlock(
    '• Google Play and Apple keep their own record of any purchase, under '
    'their policies rather than ours. Deleting your Carbs AI account does not '
    'cancel a subscription — do that in the Play Store or the App Store.',
  ),
  LegalBlock(
    '• The totals we use to cap what the AI provider costs us in a day are '
    'counts and nothing else. They are not attached to any account, and there '
    'is nothing in them to delete.',
  ),

  LegalBlock('Removing some data without deleting your account', isHeading: true),
  LegalBlock(
    'Press and hold any meal on the home screen to remove it. To remove '
    'everything, delete the account.',
  ),
];
